### PR TITLE
update for new valheim release; handle assembly publicization via ref…

### PR DESCRIPTION
**Pull request by jpw1991**
…erence

### CODE REVIEW

**Comment by jpw1991** [comment]
This should also fix #13

**Comment by CW-Jesse** [comment]
1. Why does this say there are conflicts? Is that my doing or yours?
2. Minor, but if you wouldn't mind splitting your commits into single goals in the future, that would be nice! Again, minor, and I'm happy to merge this as is.

**Comment by jpw1991** [comment]
> Why does this say there are conflicts? Is that my doing or yours?

Good question. That's weird. Huh. I'm missing write access to see what the conflicts are (just greyed out for me).

image

> Minor, but if you wouldn't mind splitting your commits into single goals in the future, that would be nice! Again, minor, and I'm happy to merge this as is.

Sure thing

**Comment by chrisjenda** [comment]
It appears as though you have pulled the wrong commit to use as your base, Don't worry though as I have already updated the mod from the latest commit to work with with version 0.216.9 and Issued a pull request that has no conflicts!

**Comment by jpw1991** [comment]
Yeah maybe we can just close and disregard this one

**Comment by CW-Jesse** [comment]
@jpw1991 You have been credited in the latest release, thank you!

**Pull request closed without merging**
